package com.rainhu;

/**
 * 389. Find the Difference (Easy)
 * 
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * @author: Rain Hu
 * @version: 1
 * @since: 2022/2/7
 * @apiNote: char array
 */

public class n389_FindTheDifference {
    public char findTheDifference(String s, String t){
        char[] sa = s.toCharArray();
        char[] ta = t.toCharArray();
        int sum = 0;
        for (int i = 0; i < sa.length; i++){
            sum += (ta[i] - sa[i]);
        }
        sum += ta[ta.length - 1];
        return (char)sum;
    }
}
